minimum_pre_commit_version: "3.7.0"
default_stages: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: backend-lint
        name: backend-lint
        entry: make backend-lint
        language: system
        pass_filenames: false
      - id: frontend-lint
        name: frontend-lint
        entry: make frontend-lint
        language: system
        pass_filenames: false
